name: C/C++ CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: autoconf
      run: |
          aclocal
          autoheader
          autoupdate
          automake --add-missing
          autoreconf

    - name: configure
      run: ./configure

    - name: make
      run: make

# Enable as sources fixed
#   - name: make check
#     run: make check

#   - name: make distcheck
#     run: make distcheck
